server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  # 数据源
  datasource:
    druid:
      url: jdbc:mysql://192.168.216.113:3306/eccom_room
      username: root
      password: Zmj001015.
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eccom.starter.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
